config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects, except: :destroy
  resources :users, except: :destroy
  get 'account', to: 'account#edit',	as: :account
  put 'account', to: 'account#update'
  get 'submit', to: 'home#submit', as: :submit
  post 'submit', to: 'home#submitted'
  root 'home#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  include ActiveModel::Transitions

  mount_uploader :logo, LogoUploader

  CATEGORIES = {
    'open-source' => 'Sumber Terbuka',
    'community'   => 'Komuniti',
    'personal'    => 'Peribadi',
    'commercial'  => 'Komersil'
  }

  validates :name, :description,
            :developer_name,
            :submitter_name, :submitter_email, :submitter_phone,
            :category, :state, presence: true
  validates :category, inclusion: {in: CATEGORIES.keys }
  validates :submitter_email, format: {with: Devise.email_regexp}

  state_machine do
    state :submitted
    state :selected
  end

  def developer_names
    developer_name.split(',').map(&:strip)
  end

  def developer_urls
    developer_url.split(',').map(&:strip)
  end

  def developers
    hash = Hash.new
    developer_names.each_with_index do |name, index|
      hash[name] = developer_urls[index].blank? ? '' : developer_urls[index]
    end
    hash
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::Transitions
  
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

	state_machine do
    state :active
    state :suspended
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
  	projects_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		render layout: nil
	end

	def submit
		@project = Project.new
		render layout: 'submit'
	end

	def submitted
		@project = Project.new project_params

		if @project.valid? && verify_recaptcha(:model => @project, :message => "Sila pastikan anda adalah manusia!")
			@project.save
			render 'submitted', layout: 'submit'
  	else
  		render 'submit', layout: 'submit'
  	end
	end

	def project_params
		params.require(:project).permit(:name, :url, :description, :logo, :category, :developer_name, :developer_url, :submitter_name, :submitter_email, :submitter_phone)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  layout 'application'

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title, sep=" | ")
    content_for :page_title, title.present? ? [title, sep].join('') : nil
  end

  def ensure_url(url)
    url = "http://#{url}" unless url[/\Ahttp:\/\//] || url[/\Ahttps:\/\//]
    url
  end

  def developers_string(hash)
    arrays = []
    hash.each do |key, value|
      if value.blank?
        arrays << key
      else
        arrays << link_to(key, ensure_url(value))
      end
    end
    arrays.join(', ').html_safe
  end
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<title>JOMLaunch</title>
<%= stylesheet_link_tag 'landing', media: 'all' %>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<section id="header">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 content text-center">
        <%= image_tag asset_path('jomweb-logo.svg'), alt: 'JomWeb', class: 'logo' %>
        <%= image_tag asset_path('jomlaunch.svg'), alt: 'JOMLaunch' %>
        <h3>
        	10 Oktober 2015, 8.30 pagi - 5.00 petang<br>
        	Content Malaysia Pitching Center, KL Sentral
        </h3>
        <p>JOMLaunch adalah sebuah program yang dikelolakan oleh komuniti JOMWEB, sebuah komuniti programmer dan penggiat teknologi maklumat di Malaysia bagi merai kepakaran teknologi maklumat tempatan. Ianya juga bertujuan memberi inspirasi kepada programmer lain agar lebih proaktif, membina projek dan beraspirasi meraih kejayaan yang lebih tinggi di peringkat global.</p>
        <%= link_to 'Beli Tiket', 'http://evenesis.yus.com.my/Tickets.aspx?event=192c6050-b33d-457c-afc0-11616b5f0080&source=p', class: 'btn btn-warning' %>
        <%= link_to 'Hantar Projek', submit_path, class: 'btn btn-jomlaunch' %>
      </div>
    </div>
  </div>
</section>

<section id="categories">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2>Kategori Projek</h2>
        <p class="lead">Projek-projek di JOMLaunch akan dibahagi kepada 4 kategori</p>
      </div>
    </div>
    <div class="row items">
      <div class="col-md-3 item">
        <div class="thumb"><%= image_tag asset_path('icon-open.svg'), alt: 'Sumber Terbuka' %></div>
        <h4>Sumber Terbuka</h4>
        <p>Kod aturcara diberikan secara percuma? Kategorikan projek anda sebagai sumber terbuka. Terima kasih kerana cuba mengubah dunia!</p>
      </div>
      <div class="col-md-3 item">
        <div class="thumb"><%= image_tag asset_path('icon-community.svg'), alt: 'Komuniti' %></div>
        <h4>Komuniti</h4>
        <p>Servis yang diberikan adalah percuma? Projek anda seharusnya berada didalam kategori komuniti. Teruskan berbakti!</p>
      </div>
      <div class="col-md-3 item">
        <div class="thumb"><%= image_tag asset_path('icon-personal.svg'), alt: 'Peribadi' %></div>
        <h4>Peribadi</h4>
        <p>Projek suka-suka? Kod anda masih lagi untuk tatapan diri sendiri? Kategori ini paling sesuai untuk anda. Asah produk anda hingga berjaya!</p>
      </div>
      <div class="col-md-3 item">
        <div class="thumb"><%= image_tag asset_path('icon-commercial.svg'), alt: 'Komersial' %></div>
        <h4>Komersil</h4>
        <p>Produk syarikat? Mensasarkan keuntungan? Sertai kami dengan memilih kategori komersil. Semoga anda sukses!</p>
      </div>
    </div>
  </div>
</section>

<section id="program">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-6 col-xs-12 content">
        <h3 class="title"><%= image_tag asset_path('icon-notebook.png'), class: 'icon' %>Atur Cara Program</h3>
        <ul class="list-unstyled list">
          <li><span class="time">8:30 am</span>Pendaftaran</li>
          <li><span class="time">9:00 am</span>Ucapan Aluan</li>
          <li><span class="time">09:15 am</span>Pembentangan Projek - Slot 1</li>
          <li><span class="time">10:15 am</span>Sembang Teknologi #1</li>
          <li><span class="time">10:45 am</span>Pembentangan Projek - Slot 2</li>
          <li><span class="time">11:45 am</span>Sembang Teknologi #2</li>
          <li><span class="time">12:15 am</span>Pembentangan Projek - Slot 3</li>
          <li><span class="time">13:15 am</span>Makan Tengahari</li>
          <li><span class="time">14:15 am</span>Pembentangan Projek - Slot 4</li>
          <li><span class="time">15:15 am</span>Sembang Teknologi #3</li>
          <li><span class="time">15:45 am</span>Pembentangan Projek - Slot 5</li>
          <li><span class="time">16:45 am</span>Sesi Penutup</li>
          </div>
      </div>
    </div>
  </div>
  <div id="map" class="col-xs-12"></div>
</section>

<section id="sponsors">
  <div class="container">
    <div class="col-md-3"><h2>Penaja &amp; Penyokong</h2></div>
    <div class="col-md-9 sponsor-list">
      <div class="col-md-4">
      	<%= link_to image_tag(asset_path('sponsor-finas.jpg'), alt: 'FINAS'), 'http://pitchingcentre.com.my' %>
      </div>
      <div class="col-md-4">
        <%= link_to image_tag(asset_path('sponsor-nef.jpg'), alt: 'NEF'), 'http://www.nef.org.my' %>
      </div>
      <div class="col-md-4">
        <%= link_to image_tag(asset_path('sponsor-evenesis.png'), alt: 'evenesis'), 'https://www.evenesis.com' %>
      </div>
      <div class="col-md-4">
        <%= link_to image_tag(asset_path('sponsor-katsana.png'), alt: 'Katsana'), 'https://www.katsana.com' %>
      </div>
    </div>
  </div>
</section>

<section id="cta">
  <div class="container text-center">
    <h2>Bersama Membangunkan Bidang Teknologi Maklumat Tempatan!</h2>
    <%= link_to 'Beli Tiket', 'http://evenesis.yus.com.my/Tickets.aspx?event=192c6050-b33d-457c-afc0-11616b5f0080&source=p', class: 'btn btn-warning' %>
    <%= link_to 'Hantar Projek', submit_path, class: 'btn btn-jomlaunch' %>
  </div>
</section>

<section id="credits">
  <div class="container text-center">
  	&copy;2015 JomWeb - Komuniti Programming &amp; UI/UX<br>
    Direka bentuk oleh <a href="https://dribbble.com/izuddinhelmi">Izuddin Helmi</a> &amp; Dibangunkan oleh <a href="http://azraai.me/">Ariff Azraai</a>
  </div>
</section>

<%= javascript_include_tag '//maps.googleapis.com/maps/api/js?sensor=false' %>
<%= javascript_include_tag 'landing' %>
</body>
</html>

app/views/home/submit.html.erb
<% page_title 'Hantar Projek' %>

<%= simple_form_for @project, url: submit_path do |f| %>
	<div class="container">
		<h2>Hantar Projek</h2>
		<p class="lead">Hantar penyertaan anda untuk dipersembahkan pada 10 Oktober 2015!</p>

		<% @project.errors[:base].each do |error| %><div class="alert alert-danger"><%= error %></div><% end %>

		<%= field_set_tag 'Maklumat Projek' do %>
			<div class="row">
				<div class="col-md-4"><%= f.input :name, label: 'Nama Projek', error: 'wajib diisi' %></div>
				<div class="col-md-4"><%= f.input :url, label: 'URL (jika ada)' %></div>
				<div class="col-md-4"><%= f.input :category, label: 'Kategori Projek', collection: Project::CATEGORIES.invert, error: 'wajib dipilih' %></div>
			</div>

			<%= f.input :description, input_html: {rows: 5}, label: 'Keterangan', error: 'wajib diisi' %>

			<div class="row">
				<div class="col-md-4"><%= f.input :logo, as: :file, label: 'Logo Projek (jika ada)', error: 'mestilah format yang dibenarkan (jpg, gif, png)' %></div>
			</div>
		<% end %>

		<%= field_set_tag 'Maklumat Pembangun' do %>
			<div class="row">
				<div class="col-md-4"><%= f.input :developer_name, label: 'Nama Pembangun', error: 'wajib diisi' %></div>
				<div class="col-md-4"><%= f.input :developer_url, label: 'URL Pembangun (jika ada)' %></div>
			</div>
		<% end %>

		<%= field_set_tag 'Maklumat Penghantar' do %>
			<div class="row">
				<div class="col-md-4"><%= f.input :submitter_name, label: 'Nama Penghantar', error: 'wajib diisi' %></div>
				<div class="col-md-4"><%= f.input :submitter_email, label: 'Email Penghantar', error: 'wajib diisi' %></div>
				<div class="col-md-4"><%= f.input :submitter_phone, label: 'No. Telefon Penghantar', error: 'wajib diisi' %></div>
			</div>
		<% end %>

		<%= recaptcha_tags hl: :ms %>
		<%= f.submit 'Hantar', class: 'btn btn-jomlaunch' %>
	</div>
<% end %>

app/views/home/submitted.html.erb
<% page_title 'Projek Diterima' %>

<div class="container">
	<h2>Projek Diterima</h2>
	<p class="lead">Penyertaan anda sedang dipertimbangkan. Pihak JomWeb akan menghubungi anda sekiranya terpilih.</p>
</div>

<section id="cta">
  <div class="container text-center">
    <h2>Bersama Membangunkan Bidang Teknologi Maklumat Tempatan!</h2>
    <%= link_to 'Beli Tiket', 'http://evenesis.yus.com.my/Tickets.aspx?event=192c6050-b33d-457c-afc0-11616b5f0080&source=p', class: 'btn btn-warning' %>
  </div>
</section>

<section id="sponsors">
  <div class="container">
    <div class="col-md-3"><h2>Penaja &amp; Penyokong</h2></div>
    <div class="col-md-9 sponsor-list">
      <div class="col-md-4">
      	<%= link_to image_tag(asset_path('sponsor-finas.jpg'), alt: 'FINAS'), 'http://pitchingcentre.com.my' %>
      </div>
      <div class="col-md-4">
        <%= link_to image_tag(asset_path('sponsor-nef.jpg'), alt: 'NEF'), 'http://www.nef.org.my' %>
      </div>
      <div class="col-md-4">
        <%= link_to image_tag(asset_path('sponsor-evenesis.png'), alt: 'evenesis'), 'https://www.evenesis.com' %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<title><%= yield :page_title %><%= t 'app.name' %></title>
<%= stylesheet_link_tag 'application', media: 'all' %>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"><%= t '.nav.toggle' %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('app.name'), root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to t('.nav.projects'), projects_path %></li>
        <li><%= link_to t('.nav.users'), users_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('.nav.sign_out'), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
	<%= yield %>
</div>

<%= javascript_include_tag 'application' %>
<%= raw humane_flash_messages %>
</body>
</html>

app/views/layouts/submit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<title><%= yield :page_title %>JOMLaunch</title>
<%= stylesheet_link_tag 'landing', media: 'all' %>
<!--[if lt IE 9]>
<script src="https://oss.mxaxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<section id="header-short">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= image_tag asset_path('jomweb-logo.svg'), alt: 'JomWeb', class: 'logo-jomweb' %>
        <%= image_tag asset_path('jomlaunch.svg'), alt: 'JOMLaunch', class: 'logo-jomlaunch' %>
        <%= link_to 'Utama', root_path, class: 'btn btn-jomlaunch pull-right' %>
        <%= link_to 'Beli Tiket', 'http://evenesis.yus.com.my/Tickets.aspx?event=192c6050-b33d-457c-afc0-11616b5f0080&source=p', class: 'btn btn-warning pull-right' %>
      </div>
    </div>
  </div>
</section>
<%= yield %>
<section id="credits">
  <div class="container text-center">
  	&copy;2015 JomWeb - Komuniti Programming &amp; UI/UX<br>
    Direka bentuk oleh <a href="https://dribbble.com/izuddinhelmi">Izuddin Helmi</a> &amp; Dibangunkan oleh <a href="http://azraai.me/">Ariff Azraai</a>
  </div>
</section>

<%= javascript_include_tag 'submit' %>
</body>
</html>

app/views/projects/index.html.erb
<% page_title t('.title') %>
<% @projects.each_with_index do |project, index| %>
<div class="project-container">
	<% if project.logo.present? %>
		<%= link_to image_tag(project.logo.thumb.url, class: 'logo', alt: project.name), project.logo.url, target: '_blank' %>
	<% else %>
		<%= image_tag project.logo.thumb.url, class: 'logo', alt: project.name %>
	<% end %>
	<span class="count">#<%= index+1 %></span>
	<span class="label label-success"><%= Project::CATEGORIES[project.category] %></span>
	<h1>
		<%= project.name %>
		<% if project.url.present? %><small><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-new-window'), ensure_url(project.url) %></small><% end %>
	</h1>
	<p class="description"><%= project.description %></p>
	<p class="developers meta"><span><%= t '.developers' %></span> <%= h developers_string(project.developers) %></p>
	<p class="submitter meta"><span><%= t '.submitter' %></span> <%= project.submitter_name %> &lt;<%= project.submitter_email %>&gt; (<%= project.submitter_phone %>)</p>
</div>
<% end %>

app/views/projects/show.html.erb
<% page_title [@project.name, t('.title')].join(' | ') %>

<div class="container">
	<div class="project-container">
		<% if @project.logo.present? %>
			<%= link_to image_tag(@project.logo.thumb.url, class: 'logo', alt: @project.name), @project.logo.url, target: '_blank' %>
		<% else %>
			<%= image_tag @project.logo.thumb.url, class: 'logo', alt: @project.name %>
		<% end %>
		<span class="label label-success"><%= Project::CATEGORIES[@project.category] %></span>
		<h1>
			<%= @project.name %>
			<% if @project.url %><small><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-new-window'), ensure_url(@project.url) %></small><% end %>
		</h1>
		<p class="description"><%= @project.description %></p>
		<p class="developers meta"><span><%= t '.developers' %></span> <%= h developers_string(@project.developers) %></p>
		<p class="submitter meta"><span><%= t '.submitter' %></span> <%= @project.submitter_name %> &lt;<%= @project.submitter_email %>&gt; (<%= @project.submitter_phone %>)</p>
	</div>
</div>